version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  labels:
  - "pr: dependencies"
  versioning-strategy: increase
  ignore:
  - dependency-name: meow
    versions:
    - 8.1.0
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
